# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        self.central_widget = QtWidgets.QWidget(Dialog)
        self.central_widget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.central_widget.setObjectName("central_widget")
        self.temp_bg = QtWidgets.QLabel(self.central_widget)
        self.temp_bg.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.temp_bg.setStyleSheet("")
        self.temp_bg.setText("")
        self.temp_bg.setPixmap(QtGui.QPixmap(":/bgimg/bg1.png"))
        self.temp_bg.setScaledContents(True)
        self.temp_bg.setObjectName("temp_bg")
        self.login_div = QtWidgets.QWidget(self.central_widget)
        self.login_div.setGeometry(QtCore.QRect(640, 0, 640, 720))
        self.login_div.setObjectName("login_div")
        self.login_content_container = QtWidgets.QWidget(self.login_div)
        self.login_content_container.setGeometry(QtCore.QRect(0, 90, 641, 581))
        self.login_content_container.setObjectName("login_content_container")
        self.login_content = QtWidgets.QWidget(self.login_content_container)
        self.login_content.setGeometry(QtCore.QRect(20, 0, 501, 581))
        self.login_content.setObjectName("login_content")
        self.login_form = QtWidgets.QWidget(self.login_content)
        self.login_form.setGeometry(QtCore.QRect(0, 0, 501, 471))
        self.login_form.setStyleSheet("#login_form {\n"
"    background-color: rgb(255, 255, 255, 168.5);\n"
"    border-radius: 35px;\n"
"}")
        self.login_form.setObjectName("login_form")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.login_form)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.login_form_content = QtWidgets.QWidget(self.login_form)
        self.login_form_content.setObjectName("login_form_content")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.login_form_content)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.header_title = QtWidgets.QLabel(self.login_form_content)
        font = QtGui.QFont()
        font.setFamily("VT323")
        font.setPointSize(43)
        font.setBold(False)
        font.setWeight(50)
        self.header_title.setFont(font)
        self.header_title.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.header_title.setWordWrap(False)
        self.header_title.setIndent(0)
        self.header_title.setObjectName("header_title")
        self.verticalLayout_2.addWidget(self.header_title)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.username_div = QtWidgets.QWidget(self.login_form_content)
        self.username_div.setStyleSheet("#username_div {\n"
"    background-color: rgb(148, 187, 233);\n"
"    border-radius: 15px;\n"
"}")
        self.username_div.setObjectName("username_div")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.username_div)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.username_icon_ = QtWidgets.QPushButton(self.username_div)
        self.username_icon_.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.username_icon_.setIcon(icon)
        self.username_icon_.setIconSize(QtCore.QSize(30, 30))
        self.username_icon_.setCheckable(False)
        self.username_icon_.setChecked(False)
        self.username_icon_.setFlat(True)
        self.username_icon_.setObjectName("username_icon_")
        self.horizontalLayout_7.addWidget(self.username_icon_)
        spacerItem4 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.username_field_ = QtWidgets.QLineEdit(self.username_div)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_field_.sizePolicy().hasHeightForWidth())
        self.username_field_.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(11)
        self.username_field_.setFont(font)
        self.username_field_.setStyleSheet("#username_field_ {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}")
        self.username_field_.setFrame(False)
        self.username_field_.setObjectName("username_field_")
        self.horizontalLayout_7.addWidget(self.username_field_)
        spacerItem5 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_2.addWidget(self.username_div)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem6)
        self.password_div = QtWidgets.QWidget(self.login_form_content)
        self.password_div.setStyleSheet("#password_div {\n"
"    background-color: rgb(148, 187, 233);\n"
"    border-radius: 15px;\n"
"}")
        self.password_div.setObjectName("password_div")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.password_div)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem7 = QtWidgets.QSpacerItem(2, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.password_icon_2 = QtWidgets.QPushButton(self.password_div)
        self.password_icon_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.password_icon_2.setIcon(icon1)
        self.password_icon_2.setIconSize(QtCore.QSize(30, 30))
        self.password_icon_2.setCheckable(False)
        self.password_icon_2.setChecked(False)
        self.password_icon_2.setFlat(True)
        self.password_icon_2.setObjectName("password_icon_2")
        self.horizontalLayout_8.addWidget(self.password_icon_2)
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.password_field_ = QtWidgets.QLineEdit(self.password_div)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_field_.sizePolicy().hasHeightForWidth())
        self.password_field_.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(11)
        self.password_field_.setFont(font)
        self.password_field_.setStyleSheet("#password_field_ {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}")
        self.password_field_.setFrame(False)
        self.password_field_.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field_.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.password_field_.setClearButtonEnabled(False)
        self.password_field_.setObjectName("password_field_")
        self.horizontalLayout_8.addWidget(self.password_field_)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_2.addWidget(self.password_div)
        spacerItem10 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.login_button = QtWidgets.QPushButton(self.login_form_content)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("#login_button {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.238, y1:1, x2:0.642, y2:0.0113636, stop:0 rgba(148, 187, 233, 255), stop:0.494318 rgba(134, 168, 231, 255), stop:1 rgba(133, 148, 217, 255));\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#login_button:hover {;\n"
"    background-color: qlineargradient(spread:pad, x1:0.488, y1:1, x2:0.477227, y2:0, stop:0 rgba(238, 173, 186, 255), stop:0.664773 rgba(255, 73, 126, 255), stop:1 rgba(255, 0, 92, 255));\n"
"}")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_3.addWidget(self.login_button)
        spacerItem11 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.forgot_password_button = QtWidgets.QPushButton(self.login_form_content)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.forgot_password_button.setFont(font)
        self.forgot_password_button.setStyleSheet("#forgot_password_button {\n"
"    color: rgb(255, 19, 79);\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}\n"
"\n"
"#forgot_password_button:hover {\n"
"    color: rgb(0, 170, 255);\n"
"}")
        self.forgot_password_button.setObjectName("forgot_password_button")
        self.horizontalLayout_3.addWidget(self.forgot_password_button)
        spacerItem12 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem13 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(10, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.signed_in_checkbox = QtWidgets.QCheckBox(self.login_form_content)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.signed_in_checkbox.setFont(font)
        self.signed_in_checkbox.setStyleSheet("#signed_in_checkbox {\n"
"    color: rgb(255, 19, 79);\n"
"}")
        self.signed_in_checkbox.setObjectName("signed_in_checkbox")
        self.horizontalLayout_4.addWidget(self.signed_in_checkbox)
        spacerItem14 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem15 = QtWidgets.QSpacerItem(0, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem15)
        self.horizontalLayout_9.addWidget(self.login_form_content)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.create_account_panel = QtWidgets.QWidget(self.login_content)
        self.create_account_panel.setGeometry(QtCore.QRect(0, 500, 501, 81))
        self.create_account_panel.setStyleSheet("#create_account_panel {\n"
"    background-color: rgb(255, 255, 255, 168.5);\n"
"    border-radius: 35px;\n"
"}\n"
"    ")
        self.create_account_panel.setObjectName("create_account_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.create_account_panel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem17 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem17)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem18 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem18)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.question = QtWidgets.QLabel(self.create_account_panel)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.horizontalLayout.addWidget(self.question)
        self.signup_button = QtWidgets.QPushButton(self.create_account_panel)
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.signup_button.setFont(font)
        self.signup_button.setStyleSheet("#signup_button {\n"
"    color: rgb(255, 19, 79);\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}\n"
"\n"
"#signup_button:hover {\n"
"    color: rgb(0, 170, 255);\n"
"}")
        self.signup_button.setFlat(True)
        self.signup_button.setObjectName("signup_button")
        self.horizontalLayout.addWidget(self.signup_button)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem19 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem20 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem20)
        self.logo_container = QtWidgets.QPushButton(self.login_div)
        self.logo_container.setGeometry(QtCore.QRect(210, 40, 121, 121))
        self.logo_container.setStyleSheet("#logo_container {\n"
"    border: 2px solid rgb(255, 19, 79);\n"
"    border-radius: 60%;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.logo_container.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logo_container.setIcon(icon2)
        self.logo_container.setIconSize(QtCore.QSize(80, 80))
        self.logo_container.setFlat(True)
        self.logo_container.setObjectName("logo_container")
        self.widget_2 = QtWidgets.QWidget(self.central_widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 640, 720))
        font = QtGui.QFont()
        font.setFamily("VT323")
        font.setPointSize(170)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName("widget_2")
        self.subtitle = QtWidgets.QLabel(self.widget_2)
        self.subtitle.setGeometry(QtCore.QRect(110, 310, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.subtitle.setFont(font)
        self.subtitle.setStyleSheet("#subtitle {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.subtitle.setObjectName("subtitle")
        self.credits = QtWidgets.QLabel(self.widget_2)
        self.credits.setGeometry(QtCore.QRect(110, 650, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(12)
        self.credits.setFont(font)
        self.credits.setStyleSheet("#credits {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.credits.setObjectName("credits")
        self.title = QtWidgets.QLabel(self.widget_2)
        self.title.setGeometry(QtCore.QRect(100, 110, 451, 211))
        self.title.setStyleSheet("#title {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.title.setObjectName("title")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.header_title.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff134f;\">LOG IN</span></p></body></html>"))
        self.username_field_.setPlaceholderText(_translate("Dialog", "Username"))
        self.password_field_.setPlaceholderText(_translate("Dialog", "Password"))
        self.login_button.setText(_translate("Dialog", "Log In"))
        self.forgot_password_button.setText(_translate("Dialog", "Forgot Password?"))
        self.signed_in_checkbox.setText(_translate("Dialog", "Keep me signed in"))
        self.question.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff134f;\">Don\'t have an account?</span></p></body></html>"))
        self.signup_button.setText(_translate("Dialog", "Sign Up"))
        self.subtitle.setText(_translate("Dialog", "Your Chatbot Haven"))
        self.credits.setText(_translate("Dialog", "App Packing Organization ©️ 2023"))
        self.title.setText(_translate("Dialog", "AIVEN"))
import bg_rcs
import icon_rcs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
