# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1266, 720)
        self.central_widget = QtWidgets.QWidget(Dialog)
        self.central_widget.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.central_widget.setObjectName("central_widget")
        self.background_image = QtWidgets.QLabel(self.central_widget)
        self.background_image.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.background_image.setStyleSheet("#background_image {\n"
"    background-image: url(:/bgimg/bg1.png);\n"
"}")
        self.background_image.setText("")
        self.background_image.setPixmap(QtGui.QPixmap(":/bgimg/bg1.png"))
        self.background_image.setScaledContents(True)
        self.background_image.setObjectName("background_image")
        self.login_widget = QtWidgets.QWidget(self.central_widget)
        self.login_widget.setGeometry(QtCore.QRect(640, 0, 641, 721))
        self.login_widget.setObjectName("login_widget")
        self.form_group = QtWidgets.QWidget(self.login_widget)
        self.form_group.setGeometry(QtCore.QRect(0, 90, 521, 581))
        self.form_group.setObjectName("form_group")
        self.login_panel = QtWidgets.QWidget(self.form_group)
        self.login_panel.setGeometry(QtCore.QRect(0, 0, 521, 451))
        self.login_panel.setStyleSheet("#login_panel {\n"
"    background-color: rgb(255, 255, 255, 168.75);\n"
"    border-radius: 35px;\n"
"}")
        self.login_panel.setObjectName("login_panel")
        self.login_button = QtWidgets.QPushButton(self.login_panel)
        self.login_button.setGeometry(QtCore.QRect(70, 320, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.login_button.setFont(font)
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("#login_button {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: qlineargradient(spread:pad, x1:0.238, y1:1, x2:0.642, y2:0.0113636, stop:0 rgba(148, 187, 233, 255), stop:0.494318 rgba(134, 168, 231, 255), stop:1 rgba(133, 148, 217, 255));\n"
"    border: none;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"#login_button:hover {\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0.488, y1:1, x2:0.477227, y2:0, stop:0 rgba(238, 173, 186, 255), stop:0.664773 rgba(255, 73, 126, 255), stop:1 rgba(255, 0, 92, 255));\n"
"}")
        self.login_button.setCheckable(False)
        self.login_button.setChecked(False)
        self.login_button.setAutoDefault(False)
        self.login_button.setDefault(False)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.keep_signed_in_checkbox = QtWidgets.QCheckBox(self.login_panel)
        self.keep_signed_in_checkbox.setGeometry(QtCore.QRect(80, 390, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.keep_signed_in_checkbox.setFont(font)
        self.keep_signed_in_checkbox.setStyleSheet("#keep_signed_in_checkbox {\n"
"    color: rgb(255, 19, 79);\n"
"}")
        self.keep_signed_in_checkbox.setTristate(False)
        self.keep_signed_in_checkbox.setObjectName("keep_signed_in_checkbox")
        self.forgot_password_button = QtWidgets.QPushButton(self.login_panel)
        self.forgot_password_button.setGeometry(QtCore.QRect(270, 330, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.forgot_password_button.setFont(font)
        self.forgot_password_button.setStyleSheet("#forgot_password_button {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 19, 79);\n"
"}\n"
"\n"
"#forgot_password_button:hover {\n"
"    \n"
"    color: rgb(19, 153, 255);\n"
"}")
        self.forgot_password_button.setAutoDefault(False)
        self.forgot_password_button.setFlat(True)
        self.forgot_password_button.setObjectName("forgot_password_button")
        self.login_label = QtWidgets.QLabel(self.login_panel)
        self.login_label.setGeometry(QtCore.QRect(200, 70, 121, 51))
        font = QtGui.QFont()
        font.setFamily("VT323")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.login_label.setFont(font)
        self.login_label.setObjectName("login_label")
        self.username_group = QtWidgets.QWidget(self.login_panel)
        self.username_group.setGeometry(QtCore.QRect(70, 170, 371, 51))
        self.username_group.setStyleSheet("#username_group {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(148, 187, 233);\n"
"    padding: 2 2 2 55;\n"
"}")
        self.username_group.setObjectName("username_group")
        self.username_field = QtWidgets.QLineEdit(self.username_group)
        self.username_field.setGeometry(QtCore.QRect(50, 0, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(11)
        self.username_field.setFont(font)
        self.username_field.setStyleSheet("#username_field {\n"
"    \n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    padding: 2 2 2 0;\n"
"}")
        self.username_field.setInputMask("")
        self.username_field.setText("")
        self.username_field.setMaxLength(32767)
        self.username_field.setFrame(False)
        self.username_field.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_field.setDragEnabled(False)
        self.username_field.setObjectName("username_field")
        self.username_icon = QtWidgets.QLabel(self.username_group)
        self.username_icon.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.username_icon.setText("")
        self.username_icon.setPixmap(QtGui.QPixmap(":/icon/1.png"))
        self.username_icon.setScaledContents(True)
        self.username_icon.setObjectName("username_icon")
        self.password_group = QtWidgets.QWidget(self.login_panel)
        self.password_group.setGeometry(QtCore.QRect(70, 240, 371, 51))
        self.password_group.setStyleSheet("#password_group {\n"
"    border-radius: 25px;\n"
"    background-color: rgb(148, 187, 233);\n"
"    padding: 2 2 2 55;\n"
"}")
        self.password_group.setObjectName("password_group")
        self.password_field = QtWidgets.QLineEdit(self.password_group)
        self.password_field.setGeometry(QtCore.QRect(50, 0, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(11)
        self.password_field.setFont(font)
        self.password_field.setStyleSheet("#password_field {\n"
"    \n"
"    background-color: rgb(255, 255, 255, 0);\n"
"    padding: 2 2 2 0;\n"
"}")
        self.password_field.setInputMask("")
        self.password_field.setText("")
        self.password_field.setMaxLength(32767)
        self.password_field.setFrame(False)
        self.password_field.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_field.setObjectName("password_field")
        self.password_icon = QtWidgets.QLabel(self.password_group)
        self.password_icon.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.password_icon.setText("")
        self.password_icon.setPixmap(QtGui.QPixmap(":/icon/3.png"))
        self.password_icon.setScaledContents(True)
        self.password_icon.setObjectName("password_icon")
        self.slash_eye_icon = QtWidgets.QPushButton(self.password_group)
        self.slash_eye_icon.setGeometry(QtCore.QRect(320, 10, 41, 31))
        self.slash_eye_icon.setStyleSheet("#slash_eye_icon {\n"
"    \n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}")
        self.slash_eye_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slash_eye_icon.setIcon(icon)
        self.slash_eye_icon.setIconSize(QtCore.QSize(25, 25))
        self.slash_eye_icon.setCheckable(True)
        self.slash_eye_icon.setChecked(False)
        self.slash_eye_icon.setAutoRepeat(True)
        self.slash_eye_icon.setFlat(True)
        self.slash_eye_icon.setObjectName("slash_eye_icon")
        self.eye_icon = QtWidgets.QPushButton(self.password_group)
        self.eye_icon.setGeometry(QtCore.QRect(320, 10, 41, 31))
        self.eye_icon.setStyleSheet("#eye_icon {\n"
"    background-color: rgb(255, 255, 255, 0);\n"
"}")
        self.eye_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/7.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eye_icon.setIcon(icon1)
        self.eye_icon.setIconSize(QtCore.QSize(25, 25))
        self.eye_icon.setCheckable(True)
        self.eye_icon.setChecked(False)
        self.eye_icon.setAutoRepeat(False)
        self.eye_icon.setAutoExclusive(False)
        self.eye_icon.setAutoDefault(False)
        self.eye_icon.setFlat(True)
        self.eye_icon.setObjectName("eye_icon")
        self.eye_icon.raise_()
        self.password_field.raise_()
        self.password_icon.raise_()
        self.slash_eye_icon.raise_()
        self.sign_up_ad_panel = QtWidgets.QWidget(self.form_group)
        self.sign_up_ad_panel.setGeometry(QtCore.QRect(0, 500, 521, 81))
        self.sign_up_ad_panel.setStyleSheet("#sign_up_ad_panel {\n"
"    background-color: rgb(255, 255, 255, 168.75);\n"
"    border-radius: 35px;\n"
"}")
        self.sign_up_ad_panel.setObjectName("sign_up_ad_panel")
        self.to_sign_up_button = QtWidgets.QPushButton(self.sign_up_ad_panel)
        self.to_sign_up_button.setGeometry(QtCore.QRect(310, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.to_sign_up_button.setFont(font)
        self.to_sign_up_button.setStyleSheet("#to_sign_up_button {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: rgb(255, 18, 78);\n"
"}\n"
"\n"
"#to_sign_up_button:hover {\n"
"    color: rgb(19, 153, 255);\n"
"}")
        self.to_sign_up_button.setAutoDefault(False)
        self.to_sign_up_button.setFlat(True)
        self.to_sign_up_button.setObjectName("to_sign_up_button")
        self.question = QtWidgets.QLabel(self.sign_up_ad_panel)
        self.question.setGeometry(QtCore.QRect(110, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.question.setFont(font)
        self.question.setObjectName("question")
        self.logo_container = QtWidgets.QWidget(self.login_widget)
        self.logo_container.setGeometry(QtCore.QRect(210, 40, 101, 101))
        self.logo_container.setStyleSheet("#logo_container {\n"
"    border-radius: 50%;\n"
"    border: 2px solid rgb(255, 19, 79);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.logo_container.setObjectName("logo_container")
        self.logo = QtWidgets.QLabel(self.logo_container)
        self.logo.setGeometry(QtCore.QRect(20, 20, 61, 61))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/icon/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.title_widget = QtWidgets.QWidget(self.central_widget)
        self.title_widget.setGeometry(QtCore.QRect(-10, 0, 651, 721))
        self.title_widget.setObjectName("title_widget")
        self.title = QtWidgets.QLabel(self.title_widget)
        self.title.setGeometry(QtCore.QRect(90, 90, 511, 231))
        font = QtGui.QFont()
        font.setFamily("VT323")
        font.setPointSize(160)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.subtitle = QtWidgets.QLabel(self.title_widget)
        self.subtitle.setGeometry(QtCore.QRect(100, 320, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Sansation")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.subtitle.setFont(font)
        self.subtitle.setObjectName("subtitle")
        self.credits = QtWidgets.QLabel(self.title_widget)
        self.credits.setGeometry(QtCore.QRect(100, 650, 251, 16))
        self.credits.setObjectName("credits")

        self.retranslateUi(Dialog)
        self.slash_eye_icon.toggled['bool'].connect(self.slash_eye_icon.hide) # type: ignore
        self.slash_eye_icon.toggled['bool'].connect(self.eye_icon.show) # type: ignore
        self.eye_icon.toggled['bool'].connect(self.eye_icon.hide) # type: ignore
        self.eye_icon.toggled['bool'].connect(self.slash_eye_icon.show) # type: ignore
        self.slash_eye_icon.toggled['bool'].connect(self.password_field.show) # type: ignore
        self.eye_icon.toggled['bool'].connect(self.password_field.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_button.setText(_translate("Dialog", "Log In"))
        self.keep_signed_in_checkbox.setText(_translate("Dialog", "Keep me signed in"))
        self.forgot_password_button.setText(_translate("Dialog", "Forgot Password?"))
        self.login_label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff134f;\">LOG IN</span></p></body></html>"))
        self.username_field.setPlaceholderText(_translate("Dialog", "Username"))
        self.password_field.setPlaceholderText(_translate("Dialog", "Password"))
        self.to_sign_up_button.setText(_translate("Dialog", "Sign up"))
        self.question.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff134f;\">Don\'t have an account?</span></p></body></html>"))
        self.title.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">AIVEN</span></p></body></html>"))
        self.subtitle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">Your ChatBot Haven</span></p></body></html>"))
        self.credits.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ffffff;\">App Packing Organization ©️ 2023</span></p></body></html>"))
import bg_rcs
import icon_rcs


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
